// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'kr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * e​n
	 */
	LINK: string
	/**
	 * F​a​v​o​r​i​t​e
	 */
	FAVORITE: string
	/**
	 * C​a​s​i​n​o
	 */
	CASINO: string
	/**
	 * S​i​g​n​ ​I​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​ ​U​p
	 */
	SIGN_UP: string
	/**
	 * M​Y​ ​V​I​P​ ​P​E​R​K​S
	 */
	MY_VIP_PERKS: string
	/**
	 * V​I​E​W​ ​A​L​L
	 */
	VIEW_ALL: string
	/**
	 * S​P​I​N​ ​N​O​W
	 */
	SPIN_NOW: string
	/**
	 * U​n​l​o​c​k​e​d
	 */
	UNLOCKED: string
	/**
	 * F​a​v​o​r​i​t​e​s
	 */
	FAVORITES: string
	/**
	 * C​a​s​i​n​o​/​S​l​o​t​s
	 */
	CASINO_SLOTS: string
	/**
	 * S​p​o​r​t​s
	 */
	SPORTS: string
	/**
	 * S​l​o​t​s
	 */
	SLOTS: string
	/**
	 * E​-​S​p​o​r​t​s
	 */
	E_SPORTS: string
	/**
	 * V​i​r​t​u​e​ ​G​a​m​e
	 */
	VIRTUE_GAME: string
	/**
	 * M​i​n​i​ ​G​a​m​e
	 */
	MINI_GAME: string
	/**
	 * P​o​k​e​r
	 */
	POKER: string
	/**
	 * A​f​f​i​l​i​a​t​e
	 */
	AFFILIATE: string
	/**
	 * P​r​o​m​o​t​i​o​n​s
	 */
	PROMOTIONS: string
	/**
	 * P​r​o​v​a​b​l​y​ ​F​a​i​r
	 */
	PROVABLY_FAIR: string
	/**
	 * L​i​v​e​ ​S​u​p​p​o​r​t
	 */
	LIVE_SUPPORT: string
	/**
	 * L​o​g​i​n
	 */
	LOGIN: string
	/**
	 * W​e​l​c​o​m​e​ ​b​a​c​k​.​ ​P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​d​e​t​a​i​l​s
	 */
	WELCOME_BACK_PLEASE_ENTER_YOUR_DETAILS: string
	/**
	 * M​a​d​e​ ​f​o​r​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​G​a​m​b​l​e​r​s
	 */
	MADE_FOR_PROFESSIONAL_GAMBLERS: string
	/**
	 * E​m​a​i​l​ ​a​d​d​r​e​s​s
	 */
	EMAIL_ADDRESS: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d
	 */
	FORGOT_PASSWORD: string
	/**
	 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t
	 */
	DONT_HAVE_ACCOUNT: string
	/**
	 * O​r​ ​C​o​n​t​i​n​u​e​ ​W​i​t​h
	 */
	OR_CONTINUE_WITH: string
	/**
	 * H​e​y​,​ ​h​e​l​l​o​ ​�​�
	 */
	HEY_HELLO: string
	/**
	 * S​e​n​d
	 */
	SEND: string
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t
	 */
	ALREADY_HAVE_AN_ACCOUNT: string
	/**
	 * S​u​c​c​e​s​s​f​u​l​l​y​ ​S​i​g​n​U​p​!
	 */
	SUCCESSFULLY_SIGNUP: string
	/**
	 * P​r​o​m​o​t​i​o​n​ ​c​o​d​e​ ​(​o​p​t​i​o​n​a​l​)
	 */
	PROMOTION_CODE_OPTIONAL: string
	/**
	 * V​e​r​i​f​y
	 */
	VERIFY: string
	/**
	 * S​u​b​m​i​t
	 */
	SUBMIT: string
	/**
	 * S​u​c​c​e​s​s​f​u​l​l​y​ ​C​h​a​n​g​e​d​!
	 */
	SUCCESSFULLY_CHANGED: string
	/**
	 * 5​ ​V​e​r​i​f​i​c​a​t​i​o​n​ ​C​o​d​e
	 */
	FIVE_VERIFICATION_CODE: string
	/**
	 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
	 */
	ENTER_EMAIL_RESET_PASSWORD: string
	/**
	 * A​l​l​ ​C​a​t​e​g​o​r​i​e​s
	 */
	ALL_CATEGORIES: string
	/**
	 * S​l​o​t
	 */
	SLOT: string
	/**
	 * V​-​G​a​m​e
	 */
	V_GAME: string
	/**
	 * M​i​n​i​ ​G​a​m​e​s
	 */
	MINI_GAMES: string
	/**
	 * L​i​v​e​ ​S​p​o​r​t​s
	 */
	LIVE_SPORTS: string
	/**
	 * S​o​c​c​e​r
	 */
	SOCCER: string
	/**
	 * E​S​P​O​R​T​S
	 */
	ESPORTS: string
	/**
	 * T​E​N​N​I​S
	 */
	TENNIS: string
	/**
	 * B​A​S​K​E​T​B​A​L​L
	 */
	BASKETBALL: string
	/**
	 * R​U​G​B​Y
	 */
	RUGBY: string
	/**
	 * C​R​I​C​K​E​T
	 */
	CRICKET: string
	/**
	 * V​S
	 */
	VS: string
	/**
	 * L​E​A​G​U​E
	 */
	LEAGUE: string
	/**
	 * H​A​N​D​I​C​A​P
	 */
	HANDICAP: string
	/**
	 * T​O​T​A​L
	 */
	TOTAL: string
	/**
	 * M​a​i​n​ ​S​p​o​r​t​s
	 */
	MAIN_SPORTS: string
	/**
	 * B​e​s​t​ ​C​a​s​i​n​o
	 */
	BEST_CASINO: string
	/**
	 * B​e​s​t​ ​S​l​o​t
	 */
	BEST_SLOT: string
	/**
	 * R​e​c​e​n​t​ ​B​e​t​ ​D​e​p​o​s​i​t​s​ ​&​ ​W​i​t​h​d​r​a​w​a​l​ ​H​i​s​t​o​r​y
	 */
	RECENT_BET_DEPOSITS_AND_WITHDRAWAL_HISTORY: string
	/**
	 * L​A​T​E​S​T​ ​B​E​T​S
	 */
	LATEST_BETS: string
	/**
	 * R​E​C​E​N​T​ ​D​E​P​O​S​I​T​S
	 */
	RECENT_DEPOSITS: string
	/**
	 * R​E​C​E​N​T​ ​W​I​T​H​D​R​A​W​A​L​S
	 */
	RECENT_WITHDRAWALS: string
	/**
	 * G​a​m​e
	 */
	GAME: string
	/**
	 * P​l​a​y​e​r
	 */
	PLAYER: string
	/**
	 * B​e​t​ ​A​m​o​u​n​t
	 */
	BET_AMOUNT: string
	/**
	 * M​u​l​t​i​p​l​i​e​r
	 */
	MULTIPLIER: string
	/**
	 * P​R​O​F​I​T​ ​A​M​O​U​N​T
	 */
	PROFIT_AMOUNT: string
	/**
	 * S​I​G​N​ ​U​P​ ​&​ ​G​E​T​ ​D​E​P​O​S​I​T​ ​B​O​N​U​S
	 */
	SIGN_UP_GET_DEPOSIT_BONUS: string
	/**
	 * U​P​ ​T​O​ ​3​0​0​%
	 */
	UP_TO_300: string
	/**
	 * L​o​r​e​m​ ​i​p​s​u​m​ ​d​o​l​o​r​ ​s​i​t​ ​a​m​e​t​ ​c​o​n​s​e​c​t​e​t​u​r​.​ ​T​r​i​s​t​i​q​u​e​ ​i​n​ ​c​u​r​s​u​s​ ​m​a​s​s
	 */
	WWW: string
	/**
	 * G​E​T​ ​S​T​A​R​T​E​D
	 */
	GET_STARTED: string
	/**
	 * G​o​o​d​F​r​i​e​n​d​s​ ​-​ ​A​ ​c​o​o​n​s​t​r​u​c​t​i​v​e​ ​a​n​d​ ​i​n​c​l​u​s​i​v​e​ ​s​o​c​i​a​l​ ​n​e​t​w​o​r​k​ ​f​o​r​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​C​a​s​i​n​o​.​ ​W​i​t​h​ ​y​o​u​ ​e​v​e​r​y​ ​s​t​e​p​ ​o​f​ ​y​o​u​r​ ​j​o​u​r​n​e​y​.
	 */
	FOOTER_DETAIL1: string
	/**
	 * B​u​i​l​t​ ​o​n​ ​r​e​a​c​t​ ​-​-​ ​t​h​e​ ​o​p​e​n​ ​s​o​u​r​c​e​ ​s​o​f​t​w​a​r​e​ ​t​h​a​t​ ​p​o​w​e​r​s​ ​C​A​S​I​N​O​ ​a​n​d​ ​o​t​h​e​r​ ​i​n​c​l​u​s​i​v​e​ ​c​o​m​m​u​n​i​t​i​e​s​ ​M​a​d​e​ ​w​i​t​h​ ​l​o​v​e​ ​a​n​d​ ​R​u​b​y​ ​o​n​ ​R​a​i​l​s​.​ ​G​o​o​d​F​r​i​e​n​d​s​ ​©​ ​2​0​2​3
	 */
	FOOTER_DETAIL2: string
	/**
	 * G​l​o​b​a​l​ ​S​e​t​t​i​n​g​s
	 */
	GLOBAL_SETTINGS: string
	/**
	 * B​a​c​k
	 */
	BACK: string
	/**
	 * L​E​A​R​N​ ​M​O​R​E​ ​A​B​O​U​T
	 */
	LEARN_MORE_ABOUT: string
	/**
	 * A​F​F​I​L​I​A​T​E​ ​P​R​O​G​R​A​M
	 */
	AFFILIATE_PROGRAM: string
	/**
	 * W​e​ ​h​a​v​e​ ​s​p​e​c​i​a​l​ ​c​o​n​d​i​t​i​o​n​s​ ​f​o​r​ ​y​o​u​ ​t​o​ ​c​u​s​t​o​m​i​z​e​ ​y​o​u​r​ ​r​e​f​e​r​r​a​l​ ​p​r​o​g​r​a​m​!
	 */
	WE_HAVE_SPEICAL_CONDITIONS_FOR_YOU: string
	/**
	 * C​o​n​t​a​c​t​ ​u​s
	 */
	CONTACT_US: string
	/**
	 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
	 */
	FREQUENTLY_ASKED_QUESTIONS: string
	/**
	 * F​i​l​t​e​r
	 */
	FILTER: string
	/**
	 * S​e​l​e​c​t​e​d​ ​V​e​n​d​o​r​s
	 */
	SELECTED_VENDORS: string
	/**
	 * S​e​l​e​t​e​d​ ​T​y​p​e​s
	 */
	SELECTED_TYPES: string
	/**
	 * L​o​a​d​ ​m​o​r​e
	 */
	LOAD_MORE: string
	/**
	 * N​o​ ​F​a​v​o​r​i​t​e​s​ ​Y​e​t
	 */
	NO_FAVORITES_YET: string
	/**
	 * C​l​i​c​k​ ​t​h​e
	 */
	CLICK_THE: string
	/**
	 * b​y​ ​y​o​u​r​ ​f​a​v​o​u​r​i​t​e​ ​l​e​a​g​u​e​ ​o​r​ ​t​e​a​m​ ​a​n​d​ ​g​a​m​e​ ​t​o​ ​a​d​d
	 */
	BY_YOUR_FAVORITE_LEAGUE_OR_TEAM_AND_GAME_TO_ADD: string
	/**
	 * K​-​L​e​a​g​u​e
	 */
	K_LEAGUE: string
	/**
	 * H​e​l​p​ ​C​e​n​t​e​r
	 */
	HELP_CENTER: string
	/**
	 * L​o​g​i​n​ ​a​n​d​ ​G​e​t​ ​S​t​a​r​t​e​d
	 */
	LOGIN_AND_GET_STARTED: string
	/**
	 * P​l​a​y
	 */
	PLAY: string
	/**
	 * T​y​p​e
	 */
	TYPE: string
	/**
	 * M​e​r​r​c​h​a​n​t​ ​I​D
	 */
	MERRCHANT_ID: string
	/**
	 * A​m​o​u​n​t
	 */
	AMOUNT: string
	/**
	 * T​i​m​e
	 */
	TIME: string
	/**
	 * S​t​a​t​u​s
	 */
	STATUS: string
	/**
	 * D​e​p​o​s​i​t
	 */
	DEPOSIT: string
	/**
	 * s​h​o​w
	 */
	SHOW: string
	/**
	 * T​h​e​m​e
	 */
	THEME: string
	/**
	 * F​i​a​t​ ​C​u​r​r​e​n​c​y
	 */
	FIAT_CURRENCY: string
	/**
	 * S​h​o​w​ ​f​u​l​l​ ​n​a​m​e​ ​o​f​ ​c​u​r​r​e​n​c​y​ ​i​n​ ​C​r​y​p​t​o​ ​l​i​s​t
	 */
	SHOW_FULL_NAME_OF_CURRENCY_IN_CRYPTO_LIST: string
	/**
	 * L​i​g​h​t
	 */
	LIGHT: string
	/**
	 * D​a​r​k
	 */
	DARK: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	LANGUAGE: string
	/**
	 * S​i​g​n​ ​u​p​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​�​�
	 */
	SIGN_UP_SUCCESS: string
	/**
	 * S​e​n​t​ ​a​ ​a​u​t​h​ ​c​o​d​e​ ​t​o​ ​y​o​u​r​ ​e​m​a​i​l​.
	 */
	SENT_A_AUTH_CODE_TO_YOUR_EMAIL: string
	/**
	 * S​i​g​n​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​�​�
	 */
	SIGN_IN_SUCCESS: string
	/**
	 * T​o​k​e​n​ ​R​e​c​r​e​a​t​e
	 */
	TOKEN_RECREATE: string
	/**
	 * S​i​g​n​ ​o​u​t​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	SIGN_OUT_SUCCESS: string
	/**
	 * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	PASSWORD_CHANGE_SUCCESS: string
	/**
	 * P​r​o​f​i​l​e​ ​i​m​a​g​e​ ​c​h​a​n​g​e​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	PROFILE_IMAGE_CHANGE_SUCCESS: string
	/**
	 * N​i​c​k​ ​c​h​a​n​g​e​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	NICK_CHANGE_SUCCESS: string
	/**
	 * T​h​e​ ​e​m​a​i​l​ ​i​s​ ​a​ ​d​u​p​l​i​c​a​t​e​.
	 */
	EMAIL_DUPLICATE: string
	/**
	 * I​n​v​a​l​i​d​ ​h​e​a​d​e​r​ ​i​n​f​o​r​m​a​t​i​o​n​.
	 */
	INVALID_HEADER_INFORMATION: string
	/**
	 * I​n​v​a​l​i​d​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​c​o​d​e​.
	 */
	INVALID_AUTHENTICATION_CODE: string
	/**
	 * I​n​v​a​l​i​d​ ​p​r​o​m​o​ ​c​o​d​e​.
	 */
	INVALID_PROMO_CODE: string
	/**
	 * T​h​e​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t​.
	 */
	EMAIL_OR_PASSWORD_IS_INCORRECT: string
	/**
	 * I​n​v​a​l​i​d​ ​a​p​i​k​e​y
	 */
	INVALID_APIKEY: string
	/**
	 * E​m​a​i​l​ ​s​e​n​d​i​n​g​ ​f​a​i​l​e​d​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	EMAIL_SENDING_FAILED: string
	/**
	 * T​h​e​ ​t​o​k​e​n​ ​h​a​s​ ​e​x​p​i​r​e​d​.
	 */
	TOEKN_EXPIRED: string
	/**
	 * T​h​e​ ​a​g​e​n​t​'​s​ ​b​a​l​a​n​c​e​ ​i​s​ ​l​o​w​e​r​ ​t​h​a​n​ ​t​h​e​ ​u​s​e​r​'​s​ ​g​a​m​e​ ​m​o​n​e​y​.
	 */
	THE_AGENT_BALANCE_IS_LOWER: string
	/**
	 * T​h​i​s​ ​u​s​e​r​ ​d​o​e​s​ ​n​o​t​ ​e​x​i​s​t​.
	 */
	USER_DOES_NOT_EXIST: string
	/**
	 * S​e​l​e​c​t​ ​a​n​ ​p​r​o​f​i​l​e​ ​i​m​a​g​e​.
	 */
	SELECT_IMAGE: string
}

export type TranslationFunctions = {
	/**
	 * en
	 */
	LINK: () => LocalizedString
	/**
	 * Favorite
	 */
	FAVORITE: () => LocalizedString
	/**
	 * Casino
	 */
	CASINO: () => LocalizedString
	/**
	 * Sign In
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign Up
	 */
	SIGN_UP: () => LocalizedString
	/**
	 * MY VIP PERKS
	 */
	MY_VIP_PERKS: () => LocalizedString
	/**
	 * VIEW ALL
	 */
	VIEW_ALL: () => LocalizedString
	/**
	 * SPIN NOW
	 */
	SPIN_NOW: () => LocalizedString
	/**
	 * Unlocked
	 */
	UNLOCKED: () => LocalizedString
	/**
	 * Favorites
	 */
	FAVORITES: () => LocalizedString
	/**
	 * Casino/Slots
	 */
	CASINO_SLOTS: () => LocalizedString
	/**
	 * Sports
	 */
	SPORTS: () => LocalizedString
	/**
	 * Slots
	 */
	SLOTS: () => LocalizedString
	/**
	 * E-Sports
	 */
	E_SPORTS: () => LocalizedString
	/**
	 * Virtue Game
	 */
	VIRTUE_GAME: () => LocalizedString
	/**
	 * Mini Game
	 */
	MINI_GAME: () => LocalizedString
	/**
	 * Poker
	 */
	POKER: () => LocalizedString
	/**
	 * Affiliate
	 */
	AFFILIATE: () => LocalizedString
	/**
	 * Promotions
	 */
	PROMOTIONS: () => LocalizedString
	/**
	 * Provably Fair
	 */
	PROVABLY_FAIR: () => LocalizedString
	/**
	 * Live Support
	 */
	LIVE_SUPPORT: () => LocalizedString
	/**
	 * Login
	 */
	LOGIN: () => LocalizedString
	/**
	 * Welcome back. Please enter your details
	 */
	WELCOME_BACK_PLEASE_ENTER_YOUR_DETAILS: () => LocalizedString
	/**
	 * Made for professional Gamblers
	 */
	MADE_FOR_PROFESSIONAL_GAMBLERS: () => LocalizedString
	/**
	 * Email address
	 */
	EMAIL_ADDRESS: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Forgot password
	 */
	FORGOT_PASSWORD: () => LocalizedString
	/**
	 * Don't have an account
	 */
	DONT_HAVE_ACCOUNT: () => LocalizedString
	/**
	 * Or Continue With
	 */
	OR_CONTINUE_WITH: () => LocalizedString
	/**
	 * Hey, hello 👋
	 */
	HEY_HELLO: () => LocalizedString
	/**
	 * Send
	 */
	SEND: () => LocalizedString
	/**
	 * Already have an account
	 */
	ALREADY_HAVE_AN_ACCOUNT: () => LocalizedString
	/**
	 * Successfully SignUp!
	 */
	SUCCESSFULLY_SIGNUP: () => LocalizedString
	/**
	 * Promotion code (optional)
	 */
	PROMOTION_CODE_OPTIONAL: () => LocalizedString
	/**
	 * Verify
	 */
	VERIFY: () => LocalizedString
	/**
	 * Submit
	 */
	SUBMIT: () => LocalizedString
	/**
	 * Successfully Changed!
	 */
	SUCCESSFULLY_CHANGED: () => LocalizedString
	/**
	 * 5 Verification Code
	 */
	FIVE_VERIFICATION_CODE: () => LocalizedString
	/**
	 * Enter your email address to reset your password
	 */
	ENTER_EMAIL_RESET_PASSWORD: () => LocalizedString
	/**
	 * All Categories
	 */
	ALL_CATEGORIES: () => LocalizedString
	/**
	 * Slot
	 */
	SLOT: () => LocalizedString
	/**
	 * V-Game
	 */
	V_GAME: () => LocalizedString
	/**
	 * Mini Games
	 */
	MINI_GAMES: () => LocalizedString
	/**
	 * Live Sports
	 */
	LIVE_SPORTS: () => LocalizedString
	/**
	 * Soccer
	 */
	SOCCER: () => LocalizedString
	/**
	 * ESPORTS
	 */
	ESPORTS: () => LocalizedString
	/**
	 * TENNIS
	 */
	TENNIS: () => LocalizedString
	/**
	 * BASKETBALL
	 */
	BASKETBALL: () => LocalizedString
	/**
	 * RUGBY
	 */
	RUGBY: () => LocalizedString
	/**
	 * CRICKET
	 */
	CRICKET: () => LocalizedString
	/**
	 * VS
	 */
	VS: () => LocalizedString
	/**
	 * LEAGUE
	 */
	LEAGUE: () => LocalizedString
	/**
	 * HANDICAP
	 */
	HANDICAP: () => LocalizedString
	/**
	 * TOTAL
	 */
	TOTAL: () => LocalizedString
	/**
	 * Main Sports
	 */
	MAIN_SPORTS: () => LocalizedString
	/**
	 * Best Casino
	 */
	BEST_CASINO: () => LocalizedString
	/**
	 * Best Slot
	 */
	BEST_SLOT: () => LocalizedString
	/**
	 * Recent Bet Deposits & Withdrawal History
	 */
	RECENT_BET_DEPOSITS_AND_WITHDRAWAL_HISTORY: () => LocalizedString
	/**
	 * LATEST BETS
	 */
	LATEST_BETS: () => LocalizedString
	/**
	 * RECENT DEPOSITS
	 */
	RECENT_DEPOSITS: () => LocalizedString
	/**
	 * RECENT WITHDRAWALS
	 */
	RECENT_WITHDRAWALS: () => LocalizedString
	/**
	 * Game
	 */
	GAME: () => LocalizedString
	/**
	 * Player
	 */
	PLAYER: () => LocalizedString
	/**
	 * Bet Amount
	 */
	BET_AMOUNT: () => LocalizedString
	/**
	 * Multiplier
	 */
	MULTIPLIER: () => LocalizedString
	/**
	 * PROFIT AMOUNT
	 */
	PROFIT_AMOUNT: () => LocalizedString
	/**
	 * SIGN UP & GET DEPOSIT BONUS
	 */
	SIGN_UP_GET_DEPOSIT_BONUS: () => LocalizedString
	/**
	 * UP TO 300%
	 */
	UP_TO_300: () => LocalizedString
	/**
	 * Lorem ipsum dolor sit amet consectetur. Tristique in cursus mass
	 */
	WWW: () => LocalizedString
	/**
	 * GET STARTED
	 */
	GET_STARTED: () => LocalizedString
	/**
	 * GoodFriends - A coonstructive and inclusive social network for professional Casino. With you every step of your journey.
	 */
	FOOTER_DETAIL1: () => LocalizedString
	/**
	 * Built on react -- the open source software that powers CASINO and other inclusive communities Made with love and Ruby on Rails. GoodFriends © 2023
	 */
	FOOTER_DETAIL2: () => LocalizedString
	/**
	 * Global Settings
	 */
	GLOBAL_SETTINGS: () => LocalizedString
	/**
	 * Back
	 */
	BACK: () => LocalizedString
	/**
	 * LEARN MORE ABOUT
	 */
	LEARN_MORE_ABOUT: () => LocalizedString
	/**
	 * AFFILIATE PROGRAM
	 */
	AFFILIATE_PROGRAM: () => LocalizedString
	/**
	 * We have special conditions for you to customize your referral program!
	 */
	WE_HAVE_SPEICAL_CONDITIONS_FOR_YOU: () => LocalizedString
	/**
	 * Contact us
	 */
	CONTACT_US: () => LocalizedString
	/**
	 * Frequently Asked Questions
	 */
	FREQUENTLY_ASKED_QUESTIONS: () => LocalizedString
	/**
	 * Filter
	 */
	FILTER: () => LocalizedString
	/**
	 * Selected Vendors
	 */
	SELECTED_VENDORS: () => LocalizedString
	/**
	 * Seleted Types
	 */
	SELECTED_TYPES: () => LocalizedString
	/**
	 * Load more
	 */
	LOAD_MORE: () => LocalizedString
	/**
	 * No Favorites Yet
	 */
	NO_FAVORITES_YET: () => LocalizedString
	/**
	 * Click the
	 */
	CLICK_THE: () => LocalizedString
	/**
	 * by your favourite league or team and game to add
	 */
	BY_YOUR_FAVORITE_LEAGUE_OR_TEAM_AND_GAME_TO_ADD: () => LocalizedString
	/**
	 * K-League
	 */
	K_LEAGUE: () => LocalizedString
	/**
	 * Help Center
	 */
	HELP_CENTER: () => LocalizedString
	/**
	 * Login and Get Started
	 */
	LOGIN_AND_GET_STARTED: () => LocalizedString
	/**
	 * Play
	 */
	PLAY: () => LocalizedString
	/**
	 * Type
	 */
	TYPE: () => LocalizedString
	/**
	 * Merrchant ID
	 */
	MERRCHANT_ID: () => LocalizedString
	/**
	 * Amount
	 */
	AMOUNT: () => LocalizedString
	/**
	 * Time
	 */
	TIME: () => LocalizedString
	/**
	 * Status
	 */
	STATUS: () => LocalizedString
	/**
	 * Deposit
	 */
	DEPOSIT: () => LocalizedString
	/**
	 * show
	 */
	SHOW: () => LocalizedString
	/**
	 * Theme
	 */
	THEME: () => LocalizedString
	/**
	 * Fiat Currency
	 */
	FIAT_CURRENCY: () => LocalizedString
	/**
	 * Show full name of currency in Crypto list
	 */
	SHOW_FULL_NAME_OF_CURRENCY_IN_CRYPTO_LIST: () => LocalizedString
	/**
	 * Light
	 */
	LIGHT: () => LocalizedString
	/**
	 * Dark
	 */
	DARK: () => LocalizedString
	/**
	 * Language
	 */
	LANGUAGE: () => LocalizedString
	/**
	 * Sign up successfully 🎉
	 */
	SIGN_UP_SUCCESS: () => LocalizedString
	/**
	 * Sent a auth code to your email.
	 */
	SENT_A_AUTH_CODE_TO_YOUR_EMAIL: () => LocalizedString
	/**
	 * Sign in successfully 🎉
	 */
	SIGN_IN_SUCCESS: () => LocalizedString
	/**
	 * Token Recreate
	 */
	TOKEN_RECREATE: () => LocalizedString
	/**
	 * Sign out successfully
	 */
	SIGN_OUT_SUCCESS: () => LocalizedString
	/**
	 * Password change successfully
	 */
	PASSWORD_CHANGE_SUCCESS: () => LocalizedString
	/**
	 * Profile image change successfully
	 */
	PROFILE_IMAGE_CHANGE_SUCCESS: () => LocalizedString
	/**
	 * Nick change successfully
	 */
	NICK_CHANGE_SUCCESS: () => LocalizedString
	/**
	 * The email is a duplicate.
	 */
	EMAIL_DUPLICATE: () => LocalizedString
	/**
	 * Invalid header information.
	 */
	INVALID_HEADER_INFORMATION: () => LocalizedString
	/**
	 * Invalid authentication code.
	 */
	INVALID_AUTHENTICATION_CODE: () => LocalizedString
	/**
	 * Invalid promo code.
	 */
	INVALID_PROMO_CODE: () => LocalizedString
	/**
	 * The email or password is incorrect.
	 */
	EMAIL_OR_PASSWORD_IS_INCORRECT: () => LocalizedString
	/**
	 * Invalid apikey
	 */
	INVALID_APIKEY: () => LocalizedString
	/**
	 * Email sending failed, please try again.
	 */
	EMAIL_SENDING_FAILED: () => LocalizedString
	/**
	 * The token has expired.
	 */
	TOEKN_EXPIRED: () => LocalizedString
	/**
	 * The agent's balance is lower than the user's game money.
	 */
	THE_AGENT_BALANCE_IS_LOWER: () => LocalizedString
	/**
	 * This user does not exist.
	 */
	USER_DOES_NOT_EXIST: () => LocalizedString
	/**
	 * Select an profile image.
	 */
	SELECT_IMAGE: () => LocalizedString
}

export type Formatters = {}
